version: "2"

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/bot/.data:/usr/src/app/packages/bot/.data
      - ./packages/bot/.test-data:/usr/src/app/packages/bot/.test-data
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime-real:ro
    entrypoint:
      [
        "./entrypoint.sh",
        "bot",
        "--development.noSandbox=true",
        "--development.headed=false",
      ]
