version: "2"

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./config:/usr/src/app/config
      - /dev/shm:/dev/shm
    entrypoint: ["./entrypoint.sh", "bot", "--development.noSandbox=true"]
